Support DPDK 20.11.0(LTS).

diff --git a/app/nginx-1.16.1/auto/make b/app/nginx-1.16.1/auto/make
--- a/app/nginx-1.16.1/auto/make
+++ b/app/nginx-1.16.1/auto/make
@@ -23,13 +23,13 @@ if [ ! $FF_PATH ]; then
     echo "FF_PATH environment variable not defined, default FF_PATH=$FF_PATH"
 fi
 
-if [ ! $FF_DPDK ]; then
-    FF_DPDK=/usr/local
-    echo "FF_DPDK environment variable not defined, default FF_DPDK=$FF_DPDK"
+if [ ! $(pkg-config --exists libdpdk && echo 1) ]; then
+    echo "error: no installation of DPDK found, maybe you shuld export environment variable \`PKG_CONFIG_PATH\`"
+    exit 1
 fi
 
+CORE_LIBS="$CORE_LIBS \$(shell pkg-config --static --libs libdpdk)"
 CORE_LIBS="$CORE_LIBS -L$FF_PATH/lib -Wl,--whole-archive,-lfstack,--no-whole-archive"
-CORE_LIBS="$CORE_LIBS -L$FF_DPDK/lib -Wl,--whole-archive,-ldpdk,--no-whole-archive"
 CORE_LIBS="$CORE_LIBS -Wl,--no-whole-archive -lrt -lm -ldl -lcrypto -lpthread -lnuma"
 
 cat << END                                                     > $NGX_MAKEFILE
